---
title: Indivisible Manteca
timezone: America/Los_Angeles
collections:
  pictures:
    title: Pictures
    output: true
  posts:
    title: Posts
    output: true
  representatives:
    title: Representatives
    output: false
  successes:
    title: Successes
    output: true
  take-action-with-indivisible-manteca:
    title: Take Action With Indivisible Manteca
    output: true
  uploads:
    title: Uploads
    output: true
  we-are-manteca:
    title: We are Manteca
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    is featured: false
    main-image: 
    call-script-text: 
    event-start-date: 
    event-end-date: 
    Location: 
    RSVP-link: 
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: representatives
  values:
    phone-numbers:
      office-name: "(000) 000-0000"
    website: 
- scope:
    path: ''
    type: successes
  values:
    is featured: false
    main-image: 
    layout: media-item
- scope:
    path: ''
    type: calendar
  values:
    embed-code: 
- scope:
    path: ''
    type: becomeAMember
  values:
    main-image: 
    mailchimp-form-embed: 
subtitle: We are the CA10 Resistance!  Stopping the Trump/Denham  agenda through civic
  action.
email: Indivisiblemanteca10@gmail.com
baseurl: 
url: indivisiblemanteca.com
instagram_username: indivisible_manteca10
facebook_username: indivisiblemanteca10/
twitter_username: "@indivisibleCA10"
background-image: "/uploads/2017-03-08_1112.png"
member-count: 100
footer-title: Spread the word. Help build a movement.
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
paginate: 10
paginate_path: "/blog/page:num/"
exclude:
- Gemfile
- Gemfile.lock
google_analytics: 
theme: jekyll-theme-tactile
Field name: 
Take our survey:
- DO you support healthcare as a right?
- DO you support DACA
